# Non sleep deprivation analysis

In [ ]:
### Alternatively, load from file. copy paste this under the imports
# from pathlib import Path
# from neuropy.core.session import ProcessData
# from neuropy.core.neurons import Neurons
# import numpy as np
# data_dir = Path('/home/selinali/Documents/ms_synchrony/sessions/RatU/RatUDay2NSD')
# sess = ProcessData(data_dir)
# paradigm = np.load(sess.filePrefix.with_suffix('.paradigm.npy'),allow_pickle=True).item()
# neurons = Neurons.from_dict(np.load(sess.filePrefix.with_suffix('.neurons.stable.npy'),allow_pickle=True).item())
# start=paradigm['epochs']['start'][2]
# stop=paradigm['epochs']['stop'][2]

In [ ]:
%load_ext autoreload
%autoreload 2
from neuropy.analyses import correlations 
import numpy as np
import neuropy.analyses.ms_connectivity as msconn
import seaborn as sns
import matplotlib.pyplot as plt
import time
# get only sleep sessions
#### from sd_figure1_bs.ipynb
import subjects
bin_size = 0.001 # 1 ms
window_size = 0.02 # 20 ms
# get POST
# for i in range(len(subjects.nsd.allsess)):
#     print(subjects.nsd.allsess[i].paradigm)
# subjects.data_table(subjects.nsd.allsess)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [69]:
neurons = subjects.nsd.allsess[5].neurons

In [202]:
short_neurons = neurons.time_slice(t_start=10009,t_stop=10010)

In [203]:
x,y=2,5
correlations.cp_spike_correlations_2groups(short_neurons,[x],[y],1e-3,4e-3)-correlations.cp_spike_correlations(short_neurons,[y,x],1e-3,4e-3)[1,0]

shift 3
Bin size is 30


array([[[ 0, -1,  1,  0]]], dtype=int32)

In [204]:
correlations.cp_spike_correlations_2groups(short_neurons,[x],[y],1e-3,4e-3)

shift 3


array([[[1, 1, 1, 0]]], dtype=int32)

In [205]:
correlations.cp_spike_correlations(short_neurons,[y,x],1e-3,4e-3)[1,0]

Bin size is 30


array([1, 2, 0, 0], dtype=int32)

In [182]:
correlations.cp_spike_correlations(short_neurons,[y,x],1e-3,4e-3)[0,1]

Bin size is 30


array([2, 3, 4, 3], dtype=int32)

In [ ]:
for x in np.random.choice(neurons[0],20):
    print(x*30000)

In [ ]:
def plot_ccg(ccgs, window_size, bin_size, inds, pvals=None,pred=None,mode='even'):
    # example result - submillisecond synchrony
    window_size*=1e3
    bin_size*=1e3
    _, ax = plt.subplots()
    x,y=inds
    print(np.max(ccgs[x,y]),"here")
    # generating even-numbered bins
    if mode=='even':
        bins = np.arange(-window_size / 2-bin_size, window_size / 2+bin_size/2, bin_size)+bin_size/2
    else:
        bins = np.arange(-window_size / 2, window_size / 2+bin_size, bin_size)
    ax.bar(bins, ccgs[x,y], width=bin_size,alpha=0.5,label="ccg")
    if pred is not None: ax.bar(bins, pred[x,y], width=bin_size,alpha=0.5,label='ccg-smooth')
    if pvals is not None: ax.plot(bins, pvals[x,y]*np.max(ccgs[x,y]), label='p')
    ax.set_xlabel("Time (millisecond)")
    ax.set_ylabel("Count")
    ax.set_title(f"CCG, neuron_inds=[{x},{y}]")
    ax.legend()
    sns.despine(ax=ax)

### Population statistics


In [ ]:
msconn.routine_mean_firing_rates(subjects.nsd.allsess,
                        epochs = ["pre","post"], 
                        n_chunks = [1,3], 
                        brainstates=["REM","NREM"])

In [ ]:
nconf = msconn.NeuronsDatasetConfig(chunks_per_session=1,tight_epoch=True)
# neurons_dict = msconn.NeuronsDataset(subjects.nsd.allsess,nconf)
conf = msconn.CCGConfig()

In [ ]:
nd = msconn.NeuronsDataset(subjects.nsd.allsess[5],nconf)

In [ ]:
# %debug
ccgs=msconn.CCGDataset(nd,conf)

In [ ]:
ccgs.run_eranconv()

In [ ]:
ccgs.rescale_eranconv(0.1*1e-3)

In [ ]:
ccgs.save_plots(root=f"/home/selinali/Documents/NeuroPy/images/ccg_plots/test")

In [ ]:
msconn.routine_eranconv_save_plots(neurons_dict,subjects.nsd.allsess,eranconv_out)

In [ ]:
eranconv_info=msconn.routine_eranconv_connection_info(eranconv_out,neurons_dict) # fdr

In [ ]:
eranconv_info=msconn.routine_eranconv_connection_info(eranconv_out,neurons_dict) # bonferroni

In [ ]:
subjects.nsd.allsess[5].ripple
# TODO epoch doesn't seem to have arbitrary field slice function

In [ ]:
msconn.routine_eranconv_save_plots(neurons_dict,subjects.nsd.allsess,eranconv_out)

In [ ]:
jitter_out = msconn.routine_jitter_pairs_after_conv(eranconv_out)

In [ ]:
r.invert_selection()

In [ ]:
r=subjects.nsd.allsess[5].ripple

# jitter

In [ ]:
plot_ccg(ccgs, 0.01, 0.0001, [0,0], pvals, mode='odd')
print(ccgs[0,0].sum(),ccgs[0,0])

In [ ]:
# example result - submillisecond synchrony
ind=(0,1)
C = int(window_size/bin_size//2)
scope = 4
_, ax = plt.subplots()
# generating even-numbered bins
even_bins = np.arange(-window_size / 2-bin_size, window_size / 2+bin_size/2, bin_size)+bin_size/2
odd_bins = np.arange(-window_size / 2, window_size / 2+bin_size, bin_size)
ax.bar(even_bins[C-scope:C+scope+1], ccgsE[ind][C-scope:C+scope+1], width=bin_size,alpha=0.5,label="ccg-even") # 373 13
ax.bar(odd_bins[C-scope:C+scope+1], ccgsO[ind][C-scope:C+scope+1], width=bin_size,alpha=0.5,label="ccg-odd") # 26
# ax.bar(bins, pred[x,y], width=bin_size,alpha=0.5,label='ccg-smooth')
# ax.plot(bins, pvals[x,y]*np.max(ccgs[x,y]), label='p')
ax.set_xlabel("Time (millisecond)")
ax.set_ylabel("Count")
ax.set_title(f"CCG, neuron_inds=[{ind[0]},{ind[1]}]")
ax.legend()
sns.despine(ax=ax)

In [ ]:
# example result - submillisecond synchrony
ind=(0,1) # 100,14
C = int(window_size/bin_size//2)
scope = 4
_, ax = plt.subplots()
# generating even-numbered bins
even_bins = np.arange(-window_size / 2-bin_size, window_size / 2+bin_size/2, bin_size)+bin_size/2
odd_bins = np.arange(-window_size / 2, window_size / 2+bin_size, bin_size)
ax.bar(even_bins, ccgsE[ind], width=bin_size,alpha=0.5,label="ccg-even") # 373 13
ax.bar(odd_bins, ccgsO[ind], width=bin_size,alpha=0.5,label="ccg-odd") # 26
# ax.bar(bins, pred[x,y], width=bin_size,alpha=0.5,label='ccg-smooth')
# ax.plot(bins, pvals[x,y]*np.max(ccgs[x,y]), label='p')
ax.set_xlabel("Time (millisecond)")
ax.set_ylabel("Count")
ax.set_title(f"CCG, neuron_inds=[{ind[0]},{ind[1]}]")
ax.legend()
sns.despine(ax=ax)

In [ ]:
# example result - submillisecond synchrony
ind=(100,14)
C = int(window_size/bin_size//2)
scope = 4
_, ax = plt.subplots()
# generating even-numbered bins
even_bins = np.arange(-window_size / 2-bin_size, window_size / 2+bin_size/2, bin_size)+bin_size/2
odd_bins = np.arange(-window_size / 2, window_size / 2+bin_size, bin_size)
ax.bar(even_bins, ccgsE[ind], width=bin_size,alpha=0.5,label="ccg-even") # 373 13
ax.bar(odd_bins, ccgsO[ind], width=bin_size,alpha=0.5,label="ccg-odd") # 26
# ax.bar(bins, pred[x,y], width=bin_size,alpha=0.5,label='ccg-smooth')
# ax.plot(bins, pvals[x,y]*np.max(ccgs[x,y]), label='p')
ax.set_xlabel("Time (millisecond)")
ax.set_ylabel("Count")
ax.set_title(f"CCG, neuron_inds=[{ind[0]},{ind[1]}]")
ax.legend()
sns.despine(ax=ax)

In [ ]:
# if we allow identical spikes: randint, otherwise choice with replace=false (need to generate individually)
njitters = 2
nbins = 10
x = 5
size = np.random.randint(nbins*x//3,2*nbins*x//3)
simulated_spikes = cp.sort(cp.random.choice(nbins*x,size=size,replace=False))
print(simulated_spikes)
jittertrains=x*cp.floor(simulated_spikes/x)+cp.sort(cp.random.rand(x,size=(njitters,size)),axis=-1)

# n1_jitt_int=(jitter_width*2)*floor( n1/(jitter_width*2) ) + (jitter_width*2)*rand( 1,length(n1) )

In [ ]:
jittertrains

In [ ]:
cp.random.rand(2,2)

#### Get short testing neurons

In [ ]:
correlations.cp_spike_correlations_2groups(neurons=short_neurons,
                                           ref_neuron_inds=indices[10:20],
            neuron_inds=indices[-110:-107],
            bin_size=1*1e-3,
            window_size=20*1e-3,
            bin_mode='odd'
).shape

# 5 bins in 5ms window
# 30 samples per 1ms bin
# only ran two steps (shift=1,2) before stopping
# neuron0=30, neuron1=216, neuron2=235

### BRAINSTATE RASTER

In [ ]:
# TODO I feel like there's a function like this somewhere.. 
from neuropy.plotting import epochs
for sess in subjects.nsd.allsess:
    print()
    ax=epochs.plot_epochs(sess.brainstates,colors={
        'QW':'red','AW':'yellow','REM':'blue','NREM':'green','NOISE':'gray'
    })
    p = sess.paradigm
    for i in range(len(p.labels)):
        start,stop = p.starts[i],p.stops[i]
        ax.axvline(x=start,color="black", linestyle="--")
        ax.axvline(x=stop,color="black", linestyle="--")
        ax.text((start+stop)*0.4,0,p.labels[i])
        ax.set_title(msconn._short_session_name(sess))
        start,stop = p.starts[2],p.stops[2]
        ax.set_xlabel(f"{start:.2f},{stop:.2f},{(stop-start)/60/60/3:.2f}")

#### minimum ISI

In [ ]:
np.min([np.diff(np.unique(i)).min()*1000 for i in neurons.get_neuron_type('pyr').spiketrains])

In [ ]:
interspikes = np.concatenate([np.diff(i)*1000 for i in neurons.get_neuron_type('mua').spiketrains])
hist = np.histogram(interspikes[interspikes<2],bins=50)

In [ ]:
hist

In [ ]:
interspikes = [np.sum(np.diff(i)<1e-4)==0 for i in neurons.get_neuron_type('pyr').spiketrains]
hist = np.histogram(interspikes,bins=10)